import { FinanzamtInfo } from './finanzamtsdaten';

/**
 * Test Finanzämter for development and testing purposes
 * These are official test tax offices provided by ELSTER for testing submissions
 */
export const TEST_BUFA_MAP: Record<string, FinanzamtInfo> = {
  // Berlin Test Finanzämter
  '1194': {
    bufa: '1194',
    name: 'Berlin - Betreuungssystem',
    bundesland: 'Berlin',
    landesnummer: '11',
    finanzamtsnummer: '94',
    isTest: true,
    verfahren: 'ELF',
  },
  '1195': {
    bufa: '1195',
    name: 'Berlin - Referenzsystem',
    bundesland: 'Berlin',
    landesnummer: '11',
    finanzamtsnummer: '95',
    isTest: true,
    verfahren: 'ELF',
  },
  '1196': {
    bufa: '1196',
    name: 'Berlin - Schulungssystem',
    bundesland: 'Berlin',
    landesnummer: '11',
    finanzamtsnummer: '96',
    isTest: true,
    verfahren: 'ELF',
  },
  '1197': {
    bufa: '1197',
    name: 'Berlin - Testsystem',
    bundesland: 'Berlin',
    landesnummer: '11',
    finanzamtsnummer: '97',
    isTest: true,
    verfahren: 'ELF',
  },
  '1198': {
    bufa: '1198',
    name: 'Berlin - Abnahmesystem',
    bundesland: 'Berlin',
    landesnummer: '11',
    finanzamtsnummer: '98',
    isTest: true,
    verfahren: 'ELF',
  },

  // Bayern Test Finanzämter
  '9272': {
    bufa: '9272',
    name: 'Finanzamt SU LFS Bayern Ansbach',
    bundesland: 'Bayern',
    landesnummer: '92',
    finanzamtsnummer: '72',
    isTest: true,
    verfahren: 'ELF',
  },
  '9273': {
    bufa: '9273',
    name: 'Finanzamt SU Ausbildung AbAg',
    bundesland: 'Bayern',
    landesnummer: '92',
    finanzamtsnummer: '73',
    isTest: true,
    verfahren: 'ELF',
  },
  '9274': {
    bufa: '9274',
    name: 'Finanzamt SU Laufende Fortbildung',
    bundesland: 'Bayern',
    landesnummer: '92',
    finanzamtsnummer: '74',
    isTest: true,
    verfahren: 'ELF',
  },
  '9275': {
    bufa: '9275',
    name: 'Finanzamt SU Fortbildung neue EDV-Verf.',
    bundesland: 'Bayern',
    landesnummer: '92',
    finanzamtsnummer: '75',
    isTest: true,
    verfahren: 'ELF',
  },
  '9276': {
    bufa: '9276',
    name: 'Finanzamt SU LFS Ansbach Prüfung',
    bundesland: 'Bayern',
    landesnummer: '92',
    finanzamtsnummer: '76',
    isTest: true,
    verfahren: 'ELF',
  },
  '9277': {
    bufa: '9277',
    name: 'Finanzamt SU 277 LFS Bayern Ansbach 2',
    bundesland: 'Bayern',
    landesnummer: '92',
    finanzamtsnummer: '77',
    isTest: true,
    verfahren: 'ELF',
  },
  '9278': {
    bufa: '9278',
    name: 'Finanzamt SU 278 LFS Ansbach Prüfung 2',
    bundesland: 'Bayern',
    landesnummer: '92',
    finanzamtsnummer: '78',
    isTest: true,
    verfahren: 'ELF',
  },
  '9279': {
    bufa: '9279',
    name: 'Finanzamt SU 279 Fortbildung Bayern BIENE',
    bundesland: 'Bayern',
    landesnummer: '92',
    finanzamtsnummer: '79',
    isTest: true,
    verfahren: 'ELF',
  },
  '9280': {
    bufa: '9280',
    name: 'Finanzamt SU 280 HföD Herrsching',
    bundesland: 'Bayern',
    landesnummer: '92',
    finanzamtsnummer: '80',
    isTest: true,
    verfahren: 'ELF',
  },
  '9282': {
    bufa: '9282',
    name: 'Finanzamt LFS Bayern in Ansbach',
    bundesland: 'Bayern',
    landesnummer: '92',
    finanzamtsnummer: '82',
    isTest: true,
    verfahren: 'ELF',
  },
  '9283': {
    bufa: '9283',
    name: 'Testfinanzamt OFD Nbg. -9283-',
    bundesland: 'Bayern',
    landesnummer: '92',
    finanzamtsnummer: '83',
    isTest: true,
    verfahren: 'ELF',
  },
  '9296': {
    bufa: '9296',
    name: 'Testfinanzamt OFD Nbg. -9296-',
    bundesland: 'Bayern',
    landesnummer: '92',
    finanzamtsnummer: '96',
    isTest: true,
    verfahren: 'ELF',
  },
  '9297': {
    bufa: '9297',
    name: 'Testfinanzamt LfSt Nbg. -9297-',
    bundesland: 'Bayern',
    landesnummer: '92',
    finanzamtsnummer: '97',
    isTest: true,
    verfahren: 'ELF',
  },
  '9299': {
    bufa: '9299',
    name: 'Finanzamt Test-FA OFD Nbg.',
    bundesland: 'Bayern',
    landesnummer: '92',
    finanzamtsnummer: '99',
    isTest: true,
    verfahren: 'ELF',
  },

  '2866': {
    bufa: '2866',
    name: 'Schulungsfinanzamt Bildungszentrum Ludwigsburg',
    bundesland: 'Baden-Württemberg',
    landesnummer: '28',
    finanzamtsnummer: '66',
    isTest: true,
    verfahren: 'ZWEIER',
  },
  '9198': {
    bufa: '9198',
    name: 'Testfinanzamt OF-Bereich München',
    bundesland: 'Bayern',
    landesnummer: '91',
    finanzamtsnummer: '98',
    isTest: true,
    verfahren: 'ELF',
  },
  '3098': {
    bufa: '3098',
    name: 'Test-FA Cottbus',
    bundesland: 'Brandenburg',
    landesnummer: '30',
    finanzamtsnummer: '98',
    isTest: true,
    verfahren: 'ELF',
  },
  '2497': {
    bufa: '2497',
    name: 'Bremen - Schulungssystem',
    bundesland: 'Bremen',
    landesnummer: '24',
    finanzamtsnummer: '97',
    isTest: true,
    verfahren: 'ELF',
  },
  '2293': {
    bufa: '2293',
    name: 'Testfinanzamt Hamburg',
    bundesland: 'Hamburg',
    landesnummer: '22',
    finanzamtsnummer: '93',
    isTest: true,
    verfahren: 'ELF',
  },
  '2653': {
    bufa: '2653',
    name: 'HE Testfinanzamt',
    bundesland: 'Hessen',
    landesnummer: '26',
    finanzamtsnummer: '53',
    isTest: true,
    verfahren: 'ELF',
  },
  '4098': {
    bufa: '4098',
    name: 'Testfinanzamt Mecklenburg-Vorpommern (Automation)',
    bundesland: 'Mecklenburg-Vorpommern',
    landesnummer: '40',
    finanzamtsnummer: '98',
    isTest: true,
    verfahren: 'ELF',
  },
  '2388': {
    bufa: '2388',
    name: 'Testfinanzamt Niedersachsen',
    bundesland: 'Niedersachsen',
    landesnummer: '23',
    finanzamtsnummer: '88',
    isTest: true,
    verfahren: 'ELF',
  },
  '5400': {
    bufa: '5400',
    name: 'Testfinanzamt NRW (54)',
    bundesland: 'Nordrhein-Westfalen',
    landesnummer: '54',
    finanzamtsnummer: '00',
    isTest: true,
    verfahren: 'ELF',
  },
  '5500': {
    bufa: '5500',
    name: 'Testfinanzamt NRW (55)',
    bundesland: 'Nordrhein-Westfalen',
    landesnummer: '55',
    finanzamtsnummer: '00',
    isTest: true,
    verfahren: 'ELF',
  },
  '5600': {
    bufa: '5600',
    name: 'Testfinanzamt NRW (56)',
    bundesland: 'Nordrhein-Westfalen',
    landesnummer: '56',
    finanzamtsnummer: '00',
    isTest: true,
    verfahren: 'ELF',
  },
  '2799': {
    bufa: '2799',
    name: 'Testfinanzamt Rheinland-Pfalz',
    bundesland: 'Rheinland-Pfalz',
    landesnummer: '27',
    finanzamtsnummer: '99',
    isTest: true,
    verfahren: 'ELF',
  },
  '1096': {
    bufa: '1096',
    name: 'Testfinanzamt Saarland',
    bundesland: 'Saarland',
    landesnummer: '10',
    finanzamtsnummer: '96',
    isTest: true,
    verfahren: 'ELF',
  },
  '3248': {
    bufa: '3248',
    name: 'Testfinanzamt LRZS Sachsen',
    bundesland: 'Sachsen',
    landesnummer: '32',
    finanzamtsnummer: '48',
    isTest: true,
    verfahren: 'ELF',
  },
  '3198': {
    bufa: '3198',
    name: 'Testfinanzamt Sachsen-Anhalt',
    bundesland: 'Sachsen-Anhalt',
    landesnummer: '31',
    finanzamtsnummer: '98',
    isTest: true,
    verfahren: 'ELF',
  },
  '2138': {
    bufa: '2138',
    name: 'LFS-I Schleswig-Holstein',
    bundesland: 'Schleswig-Holstein',
    landesnummer: '21',
    finanzamtsnummer: '38',
    isTest: true,
    verfahren: 'ELF',
  },
  '4198': {
    bufa: '4198',
    name: 'Testfinanzamt Thüringen',
    bundesland: 'Thüringen',
    landesnummer: '41',
    finanzamtsnummer: '98',
    isTest: true,
    verfahren: 'ELF',
  },

  // Add more test Finanzämter for other Bundesländer below:
};
