import { FinanzamtInfo } from './finanzamtsdaten';

/**
 * Test Finanzämter for development and testing purposes
 * These are official test tax offices provided by ELSTER for testing submissions
 */
export const TEST_BUFA_MAP: Record<string, FinanzamtInfo> = {
  // Berlin Test Finanzämter
  '1194': {
    bufa: '1194',
    name: 'Berlin - Betreuungssystem',
    bundesland: 'Berlin',
    landesnummer: '11',
    finanzamtsnummer: '94',
    isTest: true,
    verfahren: 'ELF',
  },
  '1195': {
    bufa: '1195',
    name: 'Berlin - Referenzsystem',
    bundesland: 'Berlin',
    landesnummer: '11',
    finanzamtsnummer: '95',
    isTest: true,
    verfahren: 'ELF',
  },
  '1196': {
    bufa: '1196',
    name: 'Berlin - Schulungssystem',
    bundesland: 'Berlin',
    landesnummer: '11',
    finanzamtsnummer: '96',
    isTest: true,
    verfahren: 'ELF',
  },
  '1197': {
    bufa: '1197',
    name: 'Berlin - Testsystem',
    bundesland: 'Berlin',
    landesnummer: '11',
    finanzamtsnummer: '97',
    isTest: true,
    verfahren: 'ELF',
  },
  '1198': {
    bufa: '1198',
    name: 'Berlin - Abnahmesystem',
    bundesland: 'Berlin',
    landesnummer: '11',
    finanzamtsnummer: '98',
    isTest: true,
    verfahren: 'ELF',
  },

  // Bayern Test Finanzämter
  '9272': {
    bufa: '9272',
    name: 'Finanzamt SU LFS Bayern Ansbach',
    bundesland: 'Bayern',
    landesnummer: '92',
    finanzamtsnummer: '72',
    isTest: true,
    verfahren: 'ELF',
  },
  '9273': {
    bufa: '9273',
    name: 'Finanzamt SU Ausbildung AbAg',
    bundesland: 'Bayern',
    landesnummer: '92',
    finanzamtsnummer: '73',
    isTest: true,
    verfahren: 'ELF',
  },
  '9274': {
    bufa: '9274',
    name: 'Finanzamt SU Laufende Fortbildung',
    bundesland: 'Bayern',
    landesnummer: '92',
    finanzamtsnummer: '74',
    isTest: true,
    verfahren: 'ELF',
  },
  '9275': {
    bufa: '9275',
    name: 'Finanzamt SU Fortbildung neue EDV-Verf.',
    bundesland: 'Bayern',
    landesnummer: '92',
    finanzamtsnummer: '75',
    isTest: true,
    verfahren: 'ELF',
  },
  '9276': {
    bufa: '9276',
    name: 'Finanzamt SU LFS Ansbach Prüfung',
    bundesland: 'Bayern',
    landesnummer: '92',
    finanzamtsnummer: '76',
    isTest: true,
    verfahren: 'ELF',
  },
  '9277': {
    bufa: '9277',
    name: 'Finanzamt SU 277 LFS Bayern Ansbach 2',
    bundesland: 'Bayern',
    landesnummer: '92',
    finanzamtsnummer: '77',
    isTest: true,
    verfahren: 'ELF',
  },
  '9278': {
    bufa: '9278',
    name: 'Finanzamt SU 278 LFS Ansbach Prüfung 2',
    bundesland: 'Bayern',
    landesnummer: '92',
    finanzamtsnummer: '78',
    isTest: true,
    verfahren: 'ELF',
  },
  '9279': {
    bufa: '9279',
    name: 'Finanzamt SU 279 Fortbildung Bayern BIENE',
    bundesland: 'Bayern',
    landesnummer: '92',
    finanzamtsnummer: '79',
    isTest: true,
    verfahren: 'ELF',
  },
  '9280': {
    bufa: '9280',
    name: 'Finanzamt SU 280 HföD Herrsching',
    bundesland: 'Bayern',
    landesnummer: '92',
    finanzamtsnummer: '80',
    isTest: true,
    verfahren: 'ELF',
  },
  '9282': {
    bufa: '9282',
    name: 'Finanzamt LFS Bayern in Ansbach',
    bundesland: 'Bayern',
    landesnummer: '92',
    finanzamtsnummer: '82',
    isTest: true,
    verfahren: 'ELF',
  },
  '9283': {
    bufa: '9283',
    name: 'Testfinanzamt OFD Nbg. -9283-',
    bundesland: 'Bayern',
    landesnummer: '92',
    finanzamtsnummer: '83',
    isTest: true,
    verfahren: 'ELF',
  },
  '9296': {
    bufa: '9296',
    name: 'Testfinanzamt OFD Nbg. -9296-',
    bundesland: 'Bayern',
    landesnummer: '92',
    finanzamtsnummer: '96',
    isTest: true,
    verfahren: 'ELF',
  },
  '9297': {
    bufa: '9297',
    name: 'Testfinanzamt LfSt Nbg. -9297-',
    bundesland: 'Bayern',
    landesnummer: '92',
    finanzamtsnummer: '97',
    isTest: true,
    verfahren: 'ELF',
  },
  '9299': {
    bufa: '9299',
    name: 'Finanzamt Test-FA OFD Nbg.',
    bundesland: 'Bayern',
    landesnummer: '92',
    finanzamtsnummer: '99',
    isTest: true,
    verfahren: 'ELF',
  },

  // Add more test Finanzämter for other Bundesländer below:
};
